import { LocalBus, publicRoomState as localPublicRoomState } from './local-bus.js?v=7.7';
import { FirebaseBus, isFirebaseConfigured } from './firebase-bus.js?v=8.1';
import { calculateMemoryPairScore, memoryCompletionBonus } from './memory-engine.js';

const $=(id)=>document.getElementById(id);
const AVATARS=['🐻','🐱','🐼','🐰','🐯','🦊','🐧','🐸','🐨','🦁','🐵','🐶'];
let selectedAvatar='🐻';
let uid=localStorage.getItem('kmb_player_uid')||(crypto.randomUUID?.()||`u-${Date.now()}-${Math.random()}`);localStorage.setItem('kmb_player_uid',uid);
let bus=null,state=null,joined=false,joinConfirmed=false,joinTimer=null;
let firstCardId=null,faceUpIds=new Set(),optimisticMatched=new Set(),boardRoundIndex=-99,lockBoard=false;
let timerRaf=null,countdownRaf=null,previousScore=0,feedbackTimer=null;
let solo=null,soloPlayer=null,soloRoundTimer=null,soloTransitionTimer=null;
const params=new URLSearchParams(location.search),pinParam=params.get('pin'),localMode=params.get('local')==='1',soloMode=params.get('solo')==='1';
if(pinParam)$('pinInput').value=pinParam;

function nowMs(){return bus?.now?bus.now():Date.now();}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function show(id){['joinView','waitingView','countdownView','playView','roundWaitView','finishView'].forEach(x=>$(x).classList.toggle('hidden',x!==id));}
function initAvatars(){$('avatarGrid').innerHTML=AVATARS.map((a,i)=>`<button class="avatar-btn ${i===0?'active':''}" data-a="${a}" type="button">${a}</button>`).join('');$('avatarGrid').addEventListener('click',e=>{const b=e.target.closest('.avatar-btn');if(!b)return;selectedAvatar=b.dataset.a;document.querySelectorAll('.avatar-btn').forEach(x=>x.classList.toggle('active',x===b));});}
function setError(t){$('joinError').textContent=t;}
function vibrate(p){try{navigator.vibrate?.(p);}catch{}}
function readLocalRoom(pin){try{return JSON.parse(localStorage.getItem(`kwb_room_${pin}`)||'null');}catch{return null;}}

async function join(){const pin=$('pinInput').value.trim(),name=$('nameInput').value.trim();if(!/^\d{6}$/.test(pin))return setError('6자리 PIN을 입력하세요.');if(!name)return setError('이름을 입력하세요.');setError('');$('joinBtn').disabled=true;try{bus?.close();let initial=null;if(localMode){const raw=readLocalRoom(pin);if(!raw)throw new Error('로컬 데모 방을 찾을 수 없습니다. 같은 PC/브라우저에서 열어 주세요.');if(raw.config?.gameType!=='memory-pairs')throw new Error('기억력 배틀 게임방이 아닙니다.');initial=localPublicRoomState(raw);bus=new LocalBus(pin);}else{if(!isFirebaseConfigured())throw new Error('Firebase 연결 설정이 완료되지 않았습니다. 선생님에게 알려 주세요.');bus=new FirebaseBus(pin,'player');await bus.init();uid=bus.uid;initial=await bus.loadRoom();if(!initial||initial.status==='closed')throw new Error('방을 찾을 수 없습니다. PIN을 확인해 주세요.');if(initial.config?.gameType!=='memory-pairs')throw new Error('기억력 배틀 게임방이 아닙니다.');}bus.on(handleMessage);if(initial.status!=='lobby')throw new Error('이미 게임이 시작된 방입니다.');joined=true;joinConfirmed=false;localStorage.setItem(`kmb_name_${pin}`,name);localStorage.setItem(`kmb_avatar_${pin}`,selectedAvatar);$('myAvatar').textContent=selectedAvatar;$('waitingName').textContent=`${name}님, 입장 요청 중...`;show('waitingView');await bus.send('join',{uid,name,avatar:selectedAvatar});if(bus.mode==='local')bus.send('request-state',{});clearTimeout(joinTimer);joinTimer=setTimeout(()=>{if(joined&&!joinConfirmed)$('waitingName').textContent=`${name}님, 입장 확인 중...`;},5000);}catch(e){joined=false;joinConfirmed=false;clearTimeout(joinTimer);bus?.close();bus=null;setError(e?.message||'게임방에 입장하지 못했습니다.');}finally{$('joinBtn').disabled=false;}}
function handleMessage(msg){if(msg.type==='state'){state=msg.payload.room;renderState();}if(msg.type==='room-closed'){alert('선생님이 게임방을 종료했습니다.');location.href='memory-play.html';}}
function renderState(){if(!joined||!state)return;const me=state.players?.[uid];if(!me)return;if(!joinConfirmed){joinConfirmed=true;clearTimeout(joinTimer);$('myAvatar').textContent=me.avatar||selectedAvatar;$('waitingName').textContent=`${me.name}님, 입장 완료!`;previousScore=Number(me.score)||0;}if(state.status==='lobby'){stopTimer();show('waitingView');return;}if(state.status==='countdown'){show('countdownView');runCountdown();return;}if(state.status==='preview'||state.status==='playing'){show('playView');renderPlay(me);runTimer();return;}if(state.status==='round-result'){stopTimer();show('roundWaitView');renderRoundWait(me);return;}if(state.status==='finished'){stopTimer();show('finishView');renderFinish(me);}}
function runCountdown(){cancelAnimationFrame(countdownRaf);const frame=()=>{if(!state||state.status!=='countdown')return;const n=Math.max(1,Math.ceil((state.countdownEndAt-nowMs())/1000));$('playerCountdown').textContent=n;countdownRaf=requestAnimationFrame(frame);};countdownRaf=requestAnimationFrame(frame);}
function stopTimer(){cancelAnimationFrame(timerRaf);timerRaf=null;}
function stopLoops(){cancelAnimationFrame(timerRaf);cancelAnimationFrame(countdownRaf);timerRaf=countdownRaf=null;}
function localProgress(){if(!state)return 0;if(state.status==='finished')return 1;if(['lobby','countdown','preview'].includes(state.status))return Math.max(0,Number(state.roundIndex||0))/Math.max(1,Number(state.roundTotal||state.config?.roundCount||1));const total=Math.max(1,Number(state.roundTotal||state.config?.roundCount||1)),idx=Math.max(0,Number(state.roundIndex||0));if(state.status==='round-result')return Math.min(1,(idx+1)/total);const s=Number(state.roundStartAt||0),e=Number(state.roundEndAt||0),f=e>s?Math.max(0,Math.min(1,(nowMs()-s)/(e-s))):0;return Math.min(1,(idx+f)/total);}
function isBlind(){return state?.status!=='finished'&&(state?.blindActive||localProgress()>=.70);}
function updateScoreVisibility(me){const blind=isBlind();$('playerBlindBadge').classList.toggle('hidden',!blind);$('myScore').classList.toggle('hidden',blind);$('blindScoreText').classList.toggle('hidden',!blind);if(!blind&&Number.isFinite(Number(me.score)))$('myScore').textContent=(Number(me.score)||0).toLocaleString();}
function runTimer(){cancelAnimationFrame(timerRaf);const frame=()=>{if(!state||!['preview','playing'].includes(state.status))return;let end=0,duration=1;if(state.status==='preview'){end=Number(state.previewEndAt||0);duration=Math.max(1,Number(state.config?.previewTime||0)*1000);}else{end=Number(state.roundEndAt||0);duration=Math.max(1000,Number(state.config?.roundTime||60)*1000);}const remaining=Math.max(0,Math.min(duration,end-nowMs())),ratio=Math.max(0,Math.min(1,remaining/duration));$('playerTimerText').textContent=(remaining/1000).toFixed(1);$('playerTimerBar').style.width=`${ratio*100}%`;const me=state.players?.[uid];if(me)updateScoreVisibility(me);if(remaining>0)timerRaf=requestAnimationFrame(frame);};timerRaf=requestAnimationFrame(frame);}
function resetBoardIfNeeded(){if(boardRoundIndex===state.roundIndex)return;boardRoundIndex=state.roundIndex;firstCardId=null;faceUpIds=new Set();optimisticMatched=new Set();lockBoard=false;$('pairFeedback').textContent='';}
function renderPlay(me){const round=state.currentRound;if(!round)return;resetBoardIfNeeded();$('playerRoundLabel').textContent=`ROUND ${state.roundIndex+1}/${state.roundTotal}`;const matched=new Set([...(me.matchedPairIds||[]),...optimisticMatched]);$('pairProgress').textContent=`${matched.size}/${state.config.pairsPerRound}쌍`;$('comboText').textContent=`COMBO ${me.combo||0}`;updateScoreVisibility(me);const score=Number(me.score);if(Number.isFinite(score)&&score>previousScore&&!isBlind()){showScoreFloat(score-previousScore);previousScore=score;}else if(Number.isFinite(score)&&score>previousScore)previousScore=score;$('selectionHint').textContent=state.status==='preview'?'카드 위치를 기억하세요. 잠시 후 모두 뒤집힙니다.':firstCardId?'두 번째 카드를 선택하세요.':'카드 두 장을 뒤집어 같은 뜻의 짝을 찾으세요.';renderBoard(round.cards||[],matched,state.status==='preview');if((me.matchedPairIds||[]).length>=state.config.pairsPerRound)setFeedback('이번 판 완료! 다른 학생을 기다리는 중…','good');}
function textLengthClass(text){const n=Array.from(String(text||'')).length;if(n>=24)return 'text-xlong';if(n>=16)return 'text-long';if(n>=10)return 'text-medium';return 'text-short';}
function renderBoard(cards,matched,preview){$('cardBoard').innerHTML=cards.map(c=>{const up=preview||matched.has(c.pairId)||faceUpIds.has(c.id);const classes=['memory-card',`lang-${c.lang||'ko'}`,textLengthClass(c.text)];if(up)classes.push('face-up');if(matched.has(c.pairId))classes.push('matched');return `<button type="button" class="${classes.join(' ')}" data-id="${esc(c.id)}" title="${esc(c.text)}" ${preview||matched.has(c.pairId)||lockBoard?'disabled':''}><span class="card-face">${esc(c.text)}</span></button>`;}).join('');}
function findCard(id){return state?.currentRound?.cards?.find(c=>c.id===id)||null;}
function clickCard(el){if(!state||state.status!=='playing'||lockBoard||el.disabled)return;const id=el.dataset.id,card=findCard(id),me=state.players?.[uid];if(!card||!me)return;const matched=new Set([...(me.matchedPairIds||[]),...optimisticMatched]);if(matched.has(card.pairId)||faceUpIds.has(id))return;if(!firstCardId){firstCardId=id;faceUpIds.add(id);renderPlay(me);return;}const first=findCard(firstCardId);if(!first){firstCardId=id;faceUpIds=new Set([id]);renderPlay(me);return;}faceUpIds.add(id);lockBoard=true;renderPlay(me);const correct=first.pairId===card.pairId;if(correct){optimisticMatched.add(card.pairId);vibrate(35);setFeedback('정답! 위치를 잘 기억했어요.','good');const oldFirst=firstCardId;firstCardId=null;setTimeout(()=>{faceUpIds.delete(oldFirst);faceUpIds.delete(id);lockBoard=false;const currentMe=state?.players?.[uid];if(currentMe)renderPlay(currentMe);},360);if(soloMode)soloMatch(card.pairId);else bus?.send('memory-match',{uid,roundIndex:state.roundIndex,pairId:card.pairId});}else{vibrate([25,40,25]);setFeedback('다른 짝이에요. 위치를 기억하고 다시 찾아보세요!','bad');if(soloMode)soloMiss();else bus?.send('memory-miss',{uid,roundIndex:state.roundIndex});const oldFirst=firstCardId;firstCardId=null;setTimeout(()=>{faceUpIds.delete(oldFirst);faceUpIds.delete(id);lockBoard=false;const currentMe=state?.players?.[uid];if(currentMe)renderPlay(currentMe);},760);}}
function setFeedback(text,type=''){clearTimeout(feedbackTimer);const el=$('pairFeedback');el.textContent=text;el.className=`pair-feedback ${type}`;if(text&&!text.includes('완료'))feedbackTimer=setTimeout(()=>{if(el.textContent===text){el.textContent='';el.className='pair-feedback';}},1500);}
function showScoreFloat(gain){const el=$('scoreFloat');el.textContent=`+${Number(gain).toLocaleString()}`;el.classList.remove('hidden');el.style.animation='none';void el.offsetWidth;el.style.animation='floatScore .85s ease forwards';setTimeout(()=>el.classList.add('hidden'),900);}
function renderRoundWait(me){const matched=me.matchedPairIds?.length||0;$('roundWaitTitle').textContent=`${state.roundIndex+1}판 종료!`;$('roundWaitStats').textContent=`맞춘 카드 ${matched}/${state.config.pairsPerRound}쌍 · 실수 ${me.mistakes||0}회${me.completionRank?` · 완료 ${me.completionRank}번째`:''}`;}
function renderFinish(me){const players=Object.values(state.players||{}).filter(p=>Number.isFinite(Number(p.score))).sort((a,b)=>Number(b.score)-Number(a.score)||(a.name||'').localeCompare(b.name||'','ko')),rank=players.findIndex(p=>p.uid===uid)+1;$('finishName').textContent=`${me.name}님, 수고했어요!`;$('finishScore').textContent=(Number(me.score)||0).toLocaleString();$('finishRank').textContent=rank>0?`${rank}위`:'-';}

function startSolo(){try{solo=JSON.parse(localStorage.getItem('kmb_solo_payload')||'null');}catch{}if(!solo?.memory?.rounds?.length){alert('교사용 기억력 배틀 설정 화면에서 [혼자 게임]을 먼저 눌러 주세요.');location.href='memory-pairs.html';return;}uid='solo';joined=true;joinConfirmed=true;soloPlayer={uid:'solo',name:'혼자 게임',avatar:'🐻',score:0,matchedPairIds:[],matchedCount:0,mistakes:0,totalMistakes:0,combo:0,missStreak:0,roundFinishedAt:0,completionRank:0,lastGain:0,lastGainAt:0};previousScore=0;show('countdownView');const end=Date.now()+3200;state={status:'countdown',countdownEndAt:end,config:solo.config,players:{solo:soloPlayer},roundTotal:solo.memory.roundCount,roundIndex:-1};runCountdown();soloTransitionTimer=setTimeout(()=>startSoloRound(0),3250);}
function startSoloRound(index){clearTimeout(soloRoundTimer);if(index>=solo.memory.rounds.length)return finishSolo();Object.assign(soloPlayer,{matchedPairIds:[],matchedCount:0,mistakes:0,combo:0,missStreak:0,roundFinishedAt:0,completionRank:0,lastGain:0,lastGainAt:0});optimisticMatched=new Set();faceUpIds=new Set();firstCardId=null;lockBoard=false;boardRoundIndex=-99;const previewMs=Math.max(0,solo.config.previewTime*1000),base=Date.now()+120,previewEnd=previewMs?base+previewMs:0,start=previewMs?previewEnd+120:base,end=start+solo.config.roundTime*1000;state={status:previewMs?'preview':'playing',config:solo.config,players:{solo:soloPlayer},roundIndex:index,roundTotal:solo.memory.roundCount,previewEndAt:previewEnd,roundStartAt:start,roundEndAt:end,currentRound:solo.memory.rounds[index],blindActive:false};show('playView');renderPlay(soloPlayer);runTimer();if(previewMs)soloTransitionTimer=setTimeout(()=>{if(state?.roundIndex===index&&state.status==='preview'){state.status='playing';renderPlay(soloPlayer);runTimer();startSoloTimeout();}},previewMs+160);else startSoloTimeout();}
function startSoloTimeout(){clearTimeout(soloRoundTimer);const remaining=Math.max(0,state.roundEndAt-Date.now());soloRoundTimer=setTimeout(()=>finishSoloRound(),remaining+80);}
function soloMatch(pairId){if(!state||state.status!=='playing'||soloPlayer.matchedPairIds.includes(pairId))return;const at=Date.now();soloPlayer.matchedPairIds.push(pairId);soloPlayer.matchedCount=soloPlayer.matchedPairIds.length;soloPlayer.combo+=1;const attempt=soloPlayer.missStreak+1;soloPlayer.missStreak=0;const duration=solo.config.roundTime*1000,ratio=Math.max(0,Math.min(1,(state.roundEndAt-at)/duration));let points=calculateMemoryPairScore(attempt,soloPlayer.combo,ratio);if(soloPlayer.matchedCount>=solo.config.pairsPerRound&&!soloPlayer.roundFinishedAt){soloPlayer.roundFinishedAt=at;soloPlayer.completionRank=1;points+=memoryCompletionBonus(1);}soloPlayer.score+=points;soloPlayer.lastGain=points;soloPlayer.lastGainAt=at;state.players.solo={...soloPlayer};renderPlay(soloPlayer);if(soloPlayer.matchedCount>=solo.config.pairsPerRound){clearTimeout(soloRoundTimer);soloRoundTimer=setTimeout(()=>finishSoloRound(),650);}}
function soloMiss(){if(!state||state.status!=='playing')return;soloPlayer.combo=0;soloPlayer.missStreak+=1;soloPlayer.mistakes+=1;soloPlayer.totalMistakes+=1;state.players.solo={...soloPlayer};renderPlay(soloPlayer);}
function finishSoloRound(){if(!state||!['playing','preview'].includes(state.status))return;stopTimer();state.status='round-result';show('roundWaitView');renderRoundWait(soloPlayer);const next=state.roundIndex+1;soloTransitionTimer=setTimeout(()=>{if(next>=solo.memory.rounds.length)finishSolo();else startSoloRound(next);},1900);}
function finishSolo(){stopLoops();clearTimeout(soloRoundTimer);clearTimeout(soloTransitionTimer);state={...state,status:'finished',players:{solo:soloPlayer},blindActive:false};show('finishView');$('finishName').textContent='혼자 게임 완료!';$('finishScore').textContent=soloPlayer.score.toLocaleString();$('finishRank').textContent=`${solo.memory.roundCount}판 완료`;}

initAvatars();$('joinBtn').addEventListener('click',join);$('nameInput').addEventListener('keydown',e=>{if(e.key==='Enter')join();});$('cardBoard').addEventListener('click',e=>{const card=e.target.closest('.memory-card');if(card)clickCard(card);});$('homeBtn').addEventListener('click',()=>location.href='memory-play.html');window.addEventListener('beforeunload',()=>{stopLoops();clearTimeout(soloRoundTimer);clearTimeout(soloTransitionTimer);bus?.close();});if(soloMode)startSolo();else show('joinView');
