import { CATALOG, booksForSource } from './catalog.js';
import { loadByConfig } from './data-loader.js';
import { buildMemoryRounds, calculateMemoryPairScore, memoryCompletionBonus, isMemoryBlind } from './memory-engine.js';
import { LocalBus, publicRoomState as localPublicRoomState } from './local-bus.js?v=7.7';
import { FirebaseBus, isFirebaseConfigured, createUniqueFirebasePin, loadVocabularyTeacherStore, saveVocabularyTeacherStore } from './firebase-bus.js?v=8.2';
import { GameAudioEngine } from './audio-engine.js?v=7.5';
import { ensureLuckyAward, renderLuckyAward } from './lucky-award.js?v=1.6';
import { requireTeacherAccess } from './access-control.js?v=1.5';
import { createLateJoinPanel, canAcceptLateJoin } from './late-join-panel.js?v=1.0';
function buildStudentEntryUrl(pin){
  const nested=location.pathname.includes('/sentence-battle-sample/');
  const u=new URL(nested?'../join.html':'join.html',location.href);
  u.searchParams.set('pin',String(pin||''));
  return u;
}

await requireTeacherAccess({ game:'memory' });

const $=(id)=>document.getElementById(id);
const audio=new GameAudioEngine();
const AVATARS=['🐻','🐱','🐼','🐰','🐯','🦊','🐧','🐸','🐨','🦁','🐵','🐶'];
const DEMO_STUDENTS=[
  {name:'Ану',avatar:'🐰',finish:.38,accuracy:.96},{name:'Тэмүүлэн',avatar:'🐯',finish:.42,accuracy:.94},
  {name:'Номин',avatar:'🐱',finish:.48,accuracy:.91},{name:'Бат',avatar:'🐻',finish:.53,accuracy:.89},
  {name:'Саруул',avatar:'🦊',finish:.59,accuracy:.87},{name:'Мөнх',avatar:'🐼',finish:.65,accuracy:.84},
  {name:'Энхжин',avatar:'🐧',finish:.71,accuracy:.82},{name:'Оюунаа',avatar:'🐨',finish:.77,accuracy:.79},
  {name:'Төгөлдөр',avatar:'🦁',finish:.83,accuracy:.76},{name:'Марал',avatar:'🐸',finish:.90,accuracy:.73}
];

let room=null,bus=null,loop=null,botTimers=[],earlyEndTimer=null,toastTimer=null;
let sourceItems=[],currentItems=[],activeSourceKey='',draftSelection=new Set(),selectionBySource=new Map();
let lastCountdownNumber=null,lastTimerSecond=null,blindTransitionPlayed=false,currentMusicMode='normal';

const MEMORY_RECEIPT_WINDOW_MS=30*60*1000;
const MEMORY_TAP_TOLERANCE_MS=900;
function memoryHistory(){if(!room)return null;room._offlineMemoryHistory||={};return room._offlineMemoryHistory;}
function ensureMemoryRecord(index,startAt=0,endAt=0){const all=memoryHistory();if(!all)return null;const key=String(Number(index));all[key]||={index:Number(index),startAt:0,endAt:0,players:{}};if(startAt)all[key].startAt=Number(startAt);if(endAt)all[key].endAt=Number(endAt);return all[key];}
function memoryHistPlayer(hist,uid){hist.players[uid]||={matchedPairIds:[],combo:0,mistakes:0,missStreak:0,roundFinishedAt:0,completionRank:0,completionBonus:0,pairScore:0};return hist.players[uid];}
function memoryTimingOk(hist,at){const tap=Number(at);if(!hist?.startAt||!hist?.endAt||!Number.isFinite(tap))return false;if(tap<hist.startAt-1200||tap>hist.endAt+MEMORY_TAP_TOLERANCE_MS)return false;return nowMs()<=hist.endAt+MEMORY_RECEIPT_WINDOW_MS;}
function syncCurrentMemoryPlayer(p,hp){p.matchedPairIds=[...hp.matchedPairIds];p.matchedCount=hp.matchedPairIds.length;p.combo=hp.combo;p.mistakes=hp.mistakes;p.missStreak=hp.missStreak;p.roundFinishedAt=hp.roundFinishedAt;p.completionRank=hp.completionRank;p.roundScore=hp.pairScore+hp.completionBonus;}
function recomputeMemoryBonuses(hist){const done=Object.entries(hist.players).filter(([,hp])=>hp.roundFinishedAt).sort((a,b)=>a[1].roundFinishedAt-b[1].roundFinishedAt||String(a[0]).localeCompare(String(b[0])));for(const [uid,hp] of Object.entries(hist.players)){const rank=done.findIndex(([id])=>id===uid)+1,newBonus=rank?memoryCompletionBonus(rank):0,delta=newBonus-(Number(hp.completionBonus)||0);hp.completionBonus=newBonus;hp.completionRank=rank||0;if(delta&&room.players?.[uid])room.players[uid].score=(Number(room.players[uid].score)||0)+delta;if(Number(hist.index)===Number(room.roundIndex)&&room.players?.[uid])syncCurrentMemoryPlayer(room.players[uid],hp);}}


const VOCAB_TEACHER_STORE_KEY='kwb_teacher_vocabulary_v1';
let teacherVocabStore={version:1,updatedAt:0,overrides:{}},teacherVocabPromise=null,teacherVocabSyncState='local',teacherVocabSyncError='';
const originalVocabById=new Map();
function emptyStore(){return {version:1,updatedAt:0,overrides:{}};}
function normalizeStore(raw){const overrides={};if(raw?.overrides&&typeof raw.overrides==='object')Object.entries(raw.overrides).forEach(([id,r])=>{const ko=String(r?.ko||'').trim(),mn=String(r?.mn||'').trim();if(id&&ko&&mn)overrides[String(id)]={id:String(id),ko,mn,updatedAt:Number(r?.updatedAt)||0};});return {version:1,updatedAt:Number(raw?.updatedAt)||0,overrides};}
function readLocalStore(){try{return normalizeStore(JSON.parse(localStorage.getItem(VOCAB_TEACHER_STORE_KEY)||'null')||emptyStore());}catch{return emptyStore();}}
function writeLocalStore(store,{touch=true}={}){const next=normalizeStore(store);if(touch)next.updatedAt=Date.now();localStorage.setItem(VOCAB_TEACHER_STORE_KEY,JSON.stringify(next));teacherVocabStore=next;return next;}
function hasOverrides(store){return Object.keys(store?.overrides||{}).length>0;}
async function resolveStore(){const local=readLocalStore();teacherVocabStore=local;if(!isFirebaseConfigured()){teacherVocabSyncState='local';teacherVocabSyncError='Firebase 미연결: 이 PC 저장 사용';return local;}try{const remoteRaw=await loadVocabularyTeacherStore();if(!remoteRaw){if(hasOverrides(local))await saveVocabularyTeacherStore(local);teacherVocabSyncState='firebase';teacherVocabSyncError='';return local;}const remote=normalizeStore(remoteRaw);if(local.updatedAt>remote.updatedAt&&hasOverrides(local)){await saveVocabularyTeacherStore(local);teacherVocabSyncState='firebase';return local;}writeLocalStore(remote,{touch:false});teacherVocabSyncState='firebase';teacherVocabSyncError='';return remote;}catch(e){console.warn(e);teacherVocabSyncState='local';teacherVocabSyncError='Firebase 불러오기 실패: 이 PC 저장 사용';return local;}}
async function ensureStore(force=false){if(force)teacherVocabPromise=null;if(!teacherVocabPromise)teacherVocabPromise=resolveStore().catch(e=>{teacherVocabPromise=null;throw e;});teacherVocabStore=await teacherVocabPromise;return teacherVocabStore;}
function applyOverrides(items){return items.map(item=>{originalVocabById.set(String(item.id),{...item});const saved=teacherVocabStore?.overrides?.[String(item.id)];return saved?{...item,ko:saved.ko,mn:saved.mn,persistent:true}:{...item,persistent:false};});}
async function loadTeacherAwareData(config,{forceSync=false}={}){await ensureStore(forceSync);const data=await loadByConfig(config);return {...data,items:applyOverrides(data.items)};}
async function saveVocabEdit(id,ko,mn){await ensureStore(true);const cleanKo=String(ko||'').trim(),cleanMn=String(mn||'').trim();if(!cleanKo||!cleanMn)throw new Error('한국어와 몽골어를 모두 입력해 주세요.');const next=normalizeStore(teacherVocabStore);next.overrides[String(id)]={id:String(id),ko:cleanKo,mn:cleanMn,updatedAt:Date.now()};next.updatedAt=Date.now();const local=writeLocalStore(next);if(isFirebaseConfigured()){try{await saveVocabularyTeacherStore(local);teacherVocabSyncState='firebase';teacherVocabSyncError='';}catch(e){teacherVocabSyncState='local';teacherVocabSyncError='Firebase 저장 실패: 이 PC에는 저장됨';}}teacherVocabStore=local;}
async function restoreVocab(id){await ensureStore(true);const next=normalizeStore(teacherVocabStore);delete next.overrides[String(id)];next.updatedAt=Date.now();const local=writeLocalStore(next);if(isFirebaseConfigured()){try{await saveVocabularyTeacherStore(local);teacherVocabSyncState='firebase';teacherVocabSyncError='';}catch(e){teacherVocabSyncState='local';teacherVocabSyncError='Firebase 저장 실패';}}teacherVocabStore=local;}

function nowMs(){return bus?.now?bus.now():Date.now();}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function toast(text){clearTimeout(toastTimer);$('toast').textContent=text;$('toast').classList.remove('hidden');toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),2800);}
function fillCatalog(){fillBooks();$('collocationSet').innerHTML=[...CATALOG.collocationSets.map(s=>`<option value="${s.id}">${s.label}</option>`),'<option value="all">전체 1-500 랜덤</option>'].join('');}
function fillBooks(){const books=booksForSource($('sourceType').value||'snu'),keep=$('snuBook').value;$('snuBook').innerHTML=books.map(b=>`<option value="${b.id}">${b.title}</option>`).join('');if(books.some(b=>b.id===keep))$('snuBook').value=keep;fillLessons();}
function fillLessons(){const books=booksForSource($('sourceType').value||'snu'),b=books.find(x=>x.id===$('snuBook').value)||books[0];$('snuLesson').innerHTML=b.lessons.map(n=>`<option value="${n}">${n}과</option>`).join('');}
function applyLaunchParams(){const p=new URLSearchParams(location.search);const source=p.get('source');if(['preliminary','snu','sejong','topik1'].includes(source))$('sourceType').value=source;if(source==='snu'||source==='sejong')fillBooks();const book=p.get('book');const books=booksForSource($('sourceType').value||'snu');if(book&&books.some(b=>b.id===book)){$('snuBook').value=book;fillLessons();}const lesson=Number(p.get('lesson'));if(lesson&&[...$('snuLesson').options].some(o=>Number(o.value)===lesson))$('snuLesson').value=String(lesson);}
function updateSourceFields(){const t=$('sourceType').value,textbook=t==='snu'||t==='sejong';$('bookField').classList.toggle('hidden',!textbook);$('lessonField').classList.toggle('hidden',!textbook);$('collocationField').classList.toggle('hidden',t!=='topik1');}
function recommendedTimes(pairs){const n=Math.max(2,Number(pairs)||6);if(n<=4)return {preview:3,round:40};if(n===5)return {preview:3,round:50};if(n===6)return {preview:4,round:60};if(n===7)return {preview:5,round:75};return {preview:5,round:90};}
function resolveTimeValue(id,kind,pairs){const raw=$(id).value;if(raw==='auto')return recommendedTimes(pairs)[kind];return Number(raw);}
function getConfig(){const pairsPerRound=Number($('pairsPerRound').value);return {gameType:'memory-pairs',sourceType:$('sourceType').value,snuBook:$('snuBook').value,snuLesson:Number($('snuLesson').value),collocationSet:$('collocationSet').value,vocabMode:$('vocabMode').value,roundCount:Number($('roundCount').value),pairsPerRound,previewTime:resolveTimeValue('previewTime','preview',pairsPerRound),roundTime:resolveTimeValue('roundTime','round',pairsPerRound),blindAt:.70,audio:{bgmEnabled:$('bgmEnabled').checked,sfxEnabled:$('sfxEnabled').checked,volume:Number($('masterVolume').value)/100}};}
function sourceKey(c){if(c.sourceType==='preliminary')return 'preliminary';if(c.sourceType==='topik1')return `topik1:${c.collocationSet}`;return `${c.sourceType}:${c.snuBook}:${c.snuLesson}`;}
function ensureSelection(key,items){const valid=new Set(items.map(v=>v.id));if(!selectionBySource.has(key))selectionBySource.set(key,new Set(valid));else{const kept=new Set([...selectionBySource.get(key)].filter(id=>valid.has(id)));if(!kept.size)items.forEach(v=>kept.add(v.id));selectionBySource.set(key,kept);}return selectionBySource.get(key);}
function selectedItems(key,items){const set=ensureSelection(key,items);return items.filter(v=>set.has(v.id));}
function isMemoryRecommended(item){const ko=String(item?.ko||'').trim(),mn=String(item?.mn||'').trim();if(!ko||!mn)return false;if(/[\s/·,]/.test(ko))return false;if(ko.length>7||mn.length>20)return false;if(ko.endsWith('다'))return false;if(/[\/;]/.test(mn))return false;return true;}
function itemsForMode(c,items){if(c.vocabMode==='all')return [...items];if(c.vocabMode==='custom')return selectedItems(activeSourceKey,items);return items.filter(isMemoryRecommended);}
function syncSelectedBadge(){$('selectedBadge').textContent=`${currentItems.length||0}/${sourceItems.length}`;}
function updateTimeRecommendation(){const pairs=Number($('pairsPerRound').value)||6,r=recommendedTimes(pairs),autoPreview=$('previewTime').value==='auto',autoRound=$('roundTime').value==='auto';$('timeRecommendation').textContent=`권장 시간: ${pairs}쌍(${pairs*2}장) 기준 카드 공개 ${r.preview}초 · 한 판 ${r.round}초${autoPreview&&autoRound?' · 현재 자동 적용 중':''}`;}
async function refreshData(){try{updateSourceFields();const c=getConfig(),data=await loadTeacherAwareData(c);activeSourceKey=sourceKey(c);sourceItems=data.items;ensureSelection(activeSourceKey,sourceItems);currentItems=itemsForMode(c,sourceItems);syncSelectedBadge();updateTimeRecommendation();const modeLabel=c.vocabMode==='recommended'?'명사 중심 추천':c.vocabMode==='all'?'전체 어휘':'직접 선택';const caution=c.vocabMode==='recommended'&&currentItems.length<c.pairsPerRound?' · ⚠ 추천 어휘가 부족합니다. 전체 어휘 또는 직접 선택을 사용하세요.':'';$('dataSummary').textContent=`${data.title} · ${modeLabel} ${currentItems.length}/${sourceItems.length}개 · 한 판 ${c.pairsPerRound}쌍(${c.pairsPerRound*2}장) · ${c.roundCount}판 · 카드 공개 ${c.previewTime}초 · 제한 ${c.roundTime}초${caution}`;}catch(e){$('dataSummary').textContent=e?.message||'자료를 불러오지 못했습니다.';}}
async function ensureData(){const c=getConfig(),data=await loadTeacherAwareData(c);activeSourceKey=sourceKey(c);sourceItems=data.items;ensureSelection(activeSourceKey,sourceItems);currentItems=itemsForMode(c,sourceItems);syncSelectedBadge();return {title:data.title,items:currentItems};}
function validateConfig(data){const c=getConfig();if(!Number.isInteger(c.roundCount)||c.roundCount<1||c.roundCount>10)throw new Error('게임 판 수를 확인해 주세요.');if(!Number.isInteger(c.pairsPerRound)||c.pairsPerRound<2||c.pairsPerRound>10)throw new Error('카드 쌍 수를 확인해 주세요.');if(data.items.length<c.pairsPerRound){const hint=c.vocabMode==='recommended'?' 이 단원은 명사 중심 추천 어휘가 부족합니다. [어휘 유형]을 전체 어휘 또는 직접 선택으로 바꿔 주세요.':'';throw new Error(`현재 사용할 수 있는 어휘가 ${data.items.length}개입니다. 최소 ${c.pairsPerRound}개가 필요합니다.${hint}`);}if(c.previewTime<0||c.previewTime>10)throw new Error('카드 공개 시간은 0~10초 사이로 설정해 주세요.');if(c.roundTime<20||c.roundTime>180)throw new Error('제한 시간은 20~180초 사이로 설정해 주세요.');return c;}
function updateBackendStatus(){const ready=isFirebaseConfigured(),el=$('backendStatus');el.classList.toggle('ready',ready);el.innerHTML=ready?'<strong>● Firebase 실시간 연결 준비 완료</strong><span>학생들이 QR/PIN으로 각자 휴대폰에서 같은 기억력 게임방에 입장할 수 있습니다.</span>':'<strong>⚠ Firebase 설정 필요</strong><span>혼자 게임과 데모 시연은 가능하지만 실제 학생 휴대폰 입장은 Firebase 설정 후 사용할 수 있습니다.</span>';}

function updateVocabPersistenceStatus(){const saved=Object.keys(teacherVocabStore?.overrides||{}).length;$('vocabPersistenceStatus').textContent=teacherVocabSyncState==='firebase'?`· 교사 수정 ${saved}개 · ☁ Firebase 공유 저장 연결됨`:`· 교사 수정 ${saved}개 · 💾 PC 저장 사용${teacherVocabSyncError?' · '+teacherVocabSyncError:''}`;}
async function openVocabModal(){try{const c=getConfig(),data=await loadTeacherAwareData(c,{forceSync:true});activeSourceKey=sourceKey(c);sourceItems=data.items;ensureSelection(activeSourceKey,sourceItems);currentItems=itemsForMode(c,sourceItems);draftSelection=new Set(selectionBySource.get(activeSourceKey)||[]);$('vocabSearch').value='';renderVocabList();updateVocabPersistenceStatus();$('vocabModal').classList.remove('hidden');}catch(e){toast(e.message);}}
function renderVocabList(){const q=$('vocabSearch').value.trim().toLowerCase();const list=sourceItems.filter(v=>!q||v.ko.toLowerCase().includes(q)||v.mn.toLowerCase().includes(q));$('vocabList').innerHTML=list.map(v=>{const saved=Boolean(teacherVocabStore?.overrides?.[String(v.id)]);return `<div class="vocab-row ${draftSelection.has(v.id)?'selected':''}" data-row-id="${esc(v.id)}"><input class="vocab-check" type="checkbox" data-id="${esc(v.id)}" ${draftSelection.has(v.id)?'checked':''}><strong>${esc(v.ko)}</strong><span class="mn">${esc(v.mn)}</span><div class="vocab-state">${saved?(teacherVocabSyncState==='firebase'?'☁ 수정 저장됨':'💾 수정 저장됨'):'원본'}</div><div class="vocab-actions"><button type="button" data-action="edit" data-id="${esc(v.id)}">✎ 수정</button>${saved?`<button class="restore" type="button" data-action="restore" data-id="${esc(v.id)}">원본 복원</button>`:''}</div></div>`;}).join('');$('modalSelectedCount').textContent=`${draftSelection.size}개 선택`;$('modalRequirement').textContent=`최소 ${$('pairsPerRound').value}개 필요`;updateVocabPersistenceStatus();}
function closeVocabModal(){$('vocabModal').classList.add('hidden');}
function applyVocabSelection(){const need=Number($('pairsPerRound').value)||6;if(draftSelection.size<need)return toast(`한 판 ${need}쌍을 위해 최소 ${need}개를 선택해 주세요.`);selectionBySource.set(activeSourceKey,new Set(draftSelection));$('vocabMode').value='custom';closeVocabModal();refreshData();toast('직접 선택 어휘를 적용했습니다.');}
async function handleVocabAction(action,id){const item=sourceItems.find(v=>String(v.id)===String(id));if(!item)return;if(action==='edit'){const ko=prompt('한국어 표현을 수정하세요.',item.ko);if(ko===null)return;const mn=prompt('몽골어 표현을 수정하세요.',item.mn);if(mn===null)return;try{await saveVocabEdit(id,ko,mn);await refreshData();await openVocabModal();toast('어휘 수정 내용을 저장했습니다.');}catch(e){toast(e.message);}}else if(action==='restore'){try{await restoreVocab(id);await refreshData();await openVocabModal();toast('원본 어휘로 복원했습니다.');}catch(e){toast(e.message);}}}

function setupAudio(){audio.setSettings(getConfig().audio);syncAudioControls();}
function syncAudioControls(){const s=audio.getSettings(),pct=Math.round(s.volume*100);$('volumeValue').textContent=`${pct}%`;$('masterVolume').value=String(pct);$('gameBgmBtn').textContent=s.bgmEnabled?'BGM ON':'BGM OFF';$('gameSfxBtn').textContent=s.sfxEnabled?'SFX ON':'SFX OFF';}
function setMusicMode(mode){currentMusicMode=mode;const labels={lobby:'🎵 LOBBY',countdown:'⏱ COUNTDOWN',preview:'🧠 MEMORIZE',normal:'🎵 BATTLE',blind:'⚠️ TENSION',final:'🔥 FINAL'};$('musicMode').textContent=labels[mode]||labels.normal;}
function persistAndBroadcast(){if(!room||!bus)return;if(bus.mode==='local'){bus.saveRoom(room);bus.send('state',{room:localPublicRoomState(room)});}else bus.saveRoom(room).catch(e=>console.warn('room save failed',e));}
function broadcastState(){if(bus?.mode==='local'&&room)bus.send('state',{room:localPublicRoomState(room)});}
function makeLocalPin(){for(let i=0;i<40;i++){const p=String(Math.floor(100000+Math.random()*900000));if(!localStorage.getItem(`kwb_room_${p}`))return p;}return String(Math.floor(100000+Math.random()*900000));}
async function createRoom(demoMode=false){try{setupAudio();await audio.unlock();if(!demoMode&&!isFirebaseConfigured())throw new Error('실제 학생 게임방은 Firebase 연결이 필요합니다.');const data=await ensureData(),config=validateConfig(data),memory=buildMemoryRounds(data.items,config);const pin=demoMode?makeLocalPin():await createUniqueFirebasePin();room={pin,title:data.title,status:'lobby',config,players:{},memory,roundIndex:-1,roundStartAt:0,roundEndAt:0,previewEndAt:0,roundResultEndAt:0,blindActive:false,demoMode:Boolean(demoMode),roundFinishCounter:0,createdAt:Date.now()};bus?.close();if(demoMode){bus=new LocalBus(pin);bus.on(handleMessage);bus.saveRoom(room);}else{bus=new FirebaseBus(pin,'host');bus.on(handleMessage);await bus.init();room.createdAt=nowMs();await bus.createRoom(room);}if(demoMode)addDemoStudents(10,false);else persistAndBroadcast();$('setupView').classList.add('hidden');$('hostView').classList.remove('hidden');showHostSubView('lobbyView');$('roomPin').textContent=pin;const url=bus.mode==='local'?new URL('memory-play.html',location.href):buildStudentEntryUrl(pin);if(bus.mode==='local'){url.searchParams.set('pin',pin);url.searchParams.set('local','1');}$('joinUrl').textContent=url.href;$('openPlayerBtn').onclick=()=>window.open(url.href,'_blank');renderQr(url.href);createLateJoinPanel({pin,url:url.href,getStatus:()=>room?.status,enabled:()=>bus?.mode==='firebase'});renderLobby();startLoop();setMusicMode('lobby');audio.startBgm('lobby');if(demoMode)toast('가상 학생 10명이 입장했습니다. [게임 시작]을 눌러 주세요.');}catch(e){toast(e?.message||'게임방을 만들지 못했습니다.');}}
function renderQr(url){const box=$('qrBox');box.innerHTML='';if(window.QRCode)new QRCode(box,{text:url,width:170,height:170,correctLevel:QRCode.CorrectLevel.M});else box.innerHTML='<span>QR 라이브러리를 불러오지 못했습니다.<br>PIN을 사용해 주세요.</span>';}
function showHostSubView(id){['lobbyView','gameView','roundResultView','finalView'].forEach(x=>$(x).classList.toggle('hidden',x!==id));}
function addDemoStudents(limit=10,announce=true){if(!room||room.status!=='lobby')return;let added=0;DEMO_STUDENTS.slice(0,limit).forEach((s,i)=>{const uid=`memory-demo-${i+1}`;if(room.players[uid])return;room.players[uid]={uid,name:s.name,avatar:s.avatar,score:0,bot:true,finish:s.finish,accuracy:s.accuracy,matchedPairIds:[],matchedCount:0,mistakes:0,totalMistakes:0,combo:0,missStreak:0,roundFinishedAt:0,completionRank:0,lastGain:0,lastGainAt:0,roundScore:0};added++;});room.demoMode=true;persistAndBroadcast();renderLobby();if(announce&&added)audio.playChime();if(announce)toast(added?`데모 학생 ${added}명을 추가했습니다.`:'데모 학생이 이미 들어와 있습니다.');}
function handleMessage(msg){if(!room)return;if(msg.type==='join'){const {uid,name,avatar}=msg.payload||{};if(!uid||!name||!canAcceptLateJoin(room.status))return;const existing=room.players[uid];if(existing){existing.name=String(name).slice(0,20);existing.avatar=AVATARS.includes(avatar)?avatar:(existing.avatar||'🐻');existing.bot=false;}else room.players[uid]={uid,name:String(name).slice(0,20),avatar:AVATARS.includes(avatar)?avatar:'🐻',score:0,bot:false,matchedPairIds:[],matchedCount:0,mistakes:0,totalMistakes:0,combo:0,missStreak:0,roundFinishedAt:0,completionRank:0,lastGain:0,lastGainAt:0,roundScore:0,lateJoin:room.status!=='lobby',joinedAt:nowMs()};persistAndBroadcast();if(room.status==='lobby')renderLobby();else if(room.status==='round-result')renderRoundResult();else renderGame(false);}if(msg.type==='memory-match')handleMemoryMatch(msg.payload,msg.at);if(msg.type==='memory-miss')handleMemoryMiss(msg.payload,msg.at);if(msg.type==='request-state')broadcastState();}
function currentRound(){return room?.memory?.rounds?.[room.roundIndex]||null;}
function validTiming(index,at){const hist=ensureMemoryRecord(index);return memoryTimingOk(hist,at);}
function handleMemoryMatch({uid,roundIndex,pairId}={},receivedAt=null){
  if(!room)return;const p=room.players[uid],index=Number(roundIndex),at=Number(receivedAt)||nowMs(),hist=ensureMemoryRecord(index);if(!p||!memoryTimingOk(hist,at))return;
  const round=room.memory?.rounds?.[index],pid=String(pairId||''),hp=memoryHistPlayer(hist,uid);if(!round?.pairs?.some(x=>String(x.pairId)===pid)||hp.matchedPairIds.includes(pid))return;
  const before=Number(p.score)||0;hp.matchedPairIds.push(pid);hp.combo=(Number(hp.combo)||0)+1;const attempt=(Number(hp.missStreak)||0)+1;hp.missStreak=0;const duration=Math.max(1000,Number(room.config.roundTime)*1000),remainingRatio=Math.max(0,Math.min(1,(hist.endAt-at)/duration));const points=calculateMemoryPairScore(attempt,hp.combo,remainingRatio);hp.pairScore=(Number(hp.pairScore)||0)+points;p.score=before+points;if(hp.matchedPairIds.length>=round.pairs.length&&!hp.roundFinishedAt)hp.roundFinishedAt=at;recomputeMemoryBonuses(hist);if(index===room.roundIndex)syncCurrentMemoryPlayer(p,hp);p.lastGain=(Number(p.score)||0)-before;p.lastGainAt=at;if(room.status==='playing'&&index===room.roundIndex)audio.playGift(p.lastGain);persistAndBroadcast();if(index===room.roundIndex){if(room.status==='playing'){renderGame();maybeEndRoundEarly();}else if(room.status==='round-result')renderRoundResult();}else if(room.status==='finished')renderFinal();else renderRanking();
}
function handleMemoryMiss({uid,roundIndex}={},receivedAt=null){
  if(!room)return;const p=room.players[uid],index=Number(roundIndex),at=Number(receivedAt)||nowMs(),hist=ensureMemoryRecord(index);if(!p||!memoryTimingOk(hist,at))return;const hp=memoryHistPlayer(hist,uid);hp.combo=0;hp.missStreak=(Number(hp.missStreak)||0)+1;hp.mistakes=(Number(hp.mistakes)||0)+1;p.totalMistakes=(Number(p.totalMistakes)||0)+1;p.lastGain=0;p.lastGainAt=at;if(index===room.roundIndex)syncCurrentMemoryPlayer(p,hp);persistAndBroadcast();if(index===room.roundIndex&&room.status==='playing')renderGame();else if(room.status==='finished')renderFinal();
}
function resetPlayersForRound(){Object.values(room.players).forEach(p=>{p.matchedPairIds=[];p.matchedCount=0;p.mistakes=0;p.combo=0;p.missStreak=0;p.roundFinishedAt=0;p.completionRank=0;p.lastGain=0;p.lastGainAt=0;p.roundScore=0;});room.roundFinishCounter=0;}
function startGame(){if(!room||!Object.keys(room.players).length)return;setupAudio();audio.unlock();audio.stopBgm();clearBotTimers();lastCountdownNumber=null;room.status='countdown';room.countdownEndAt=nowMs()+3200;room.blindActive=false;showHostSubView('gameView');setMusicMode('countdown');persistAndBroadcast();renderGame();}
function startRound(index){if(!room||index>=room.memory.rounds.length)return finishGame();clearBotTimers();clearTimeout(earlyEndTimer);resetPlayersForRound();room.roundIndex=index;const previewMs=Math.max(0,room.config.previewTime*1000);const base=nowMs()+180;room.previewEndAt=previewMs?base+previewMs:0;room.roundStartAt=previewMs?room.previewEndAt+150:base;room.roundEndAt=room.roundStartAt+room.config.roundTime*1000;room.roundResultEndAt=0;ensureMemoryRecord(index,room.roundStartAt,room.roundEndAt);room.status=previewMs?'preview':'playing';room.blindActive=isMemoryBlind(room,room.roundStartAt);showHostSubView('gameView');setMusicMode(previewMs?'preview':'normal');audio.startBgm(previewMs?'lobby':'normal');if(!previewMs){audio.playQuestionStart();scheduleDemoRound();}persistAndBroadcast();renderGame();}
function beginPlaying(){if(!room||room.status!=='preview')return;room.status='playing';setMusicMode(room.blindActive?'blind':'normal');audio.startBgm(room.blindActive?'blind':'normal');audio.playQuestionStart();persistAndBroadcast();renderGame();scheduleDemoRound();}
function syncBlind(){if(!room||room.status!=='playing')return;const blind=isMemoryBlind(room,nowMs());if(blind!==room.blindActive){room.blindActive=blind;if(blind&&!blindTransitionPlayed){blindTransitionPlayed=true;audio.playBlindTransition();setMusicMode('blind');audio.startBgm('blind');}persistAndBroadcast();}}
function maybeEndRoundEarly(){if(!room||room.status!=='playing')return;const need=currentRound()?.pairs?.length||room.config.pairsPerRound,players=Object.values(room.players);if(players.length&&players.every(p=>(p.matchedPairIds?.length||0)>=need)){clearTimeout(earlyEndTimer);earlyEndTimer=setTimeout(()=>{if(room?.status==='playing')finishRound();},650);}}
function finishRound(){if(!room||room.status!=='playing')return;clearBotTimers();room.status='round-result';room.roundResultEndAt=nowMs()+3000;room.blindActive=isMemoryBlind(room,room.roundEndAt);persistAndBroadcast();showHostSubView('roundResultView');audio.playReveal(.8);renderRoundResult();}
function finishGame(){if(!room)return;clearBotTimers();room.status='finished';room.finishedAt=nowMs();room.blindActive=false;ensureLuckyAward(room,sortedPlayers(),room.finishedAt);persistAndBroadcast();showHostSubView('finalView');setMusicMode('final');audio.playFinish();renderFinal();}
function scheduleDemoRound(){clearBotTimers();if(!room?.demoMode||room.status!=='playing')return;const round=currentRound(),duration=room.config.roundTime*1000;if(!round)return;Object.values(room.players).filter(p=>p.bot).forEach((p,pi)=>{round.pairs.forEach((pair,j)=>{const target=Math.min(duration-700,Math.max(700,duration*(p.finish*(j+1)/round.pairs.length)+pi*35));if(Math.random()>p.accuracy){const miss=setTimeout(()=>handleMemoryMiss({uid:p.uid,roundIndex:room.roundIndex},nowMs()),Math.max(300,target-380));botTimers.push(miss);}const t=setTimeout(()=>handleMemoryMatch({uid:p.uid,roundIndex:room.roundIndex,pairId:pair.pairId},nowMs()),target);botTimers.push(t);});});}
function clearBotTimers(){botTimers.forEach(clearTimeout);botTimers=[];}
function startLoop(){if(loop)clearInterval(loop);loop=setInterval(()=>{if(!room)return;const t=nowMs();if(room.status==='countdown'){const n=Math.max(1,Math.ceil((room.countdownEndAt-t)/1000));if(n!==lastCountdownNumber){lastCountdownNumber=n;audio.playCountdown(n);}$('countdownText').textContent=n;if(t>=room.countdownEndAt)startRound(0);else renderGame(false);}else if(room.status==='preview'){if(t>=room.previewEndAt)beginPlaying();else renderGame(false);}else if(room.status==='playing'){syncBlind();const sec=Math.ceil((room.roundEndAt-t)/1000);if(sec<=3&&sec>0&&sec!==lastTimerSecond){lastTimerSecond=sec;audio.playTimerTick(sec);}if(t>=room.roundEndAt)finishRound();else renderGame(false);}else if(room.status==='round-result'&&t>=room.roundResultEndAt){const next=room.roundIndex+1;if(next>=room.memory.rounds.length)finishGame();else startRound(next);}},90);}
function renderLobby(){if(!room)return;const players=Object.values(room.players);$('playerCount').textContent=`${players.length}명`;$('startGameBtn').disabled=!players.length;$('demoInfo').classList.toggle('hidden',!room.demoMode);const el=$('playerList');el.classList.toggle('empty',!players.length);el.innerHTML=players.length?players.map(p=>`<div class="player-chip"><span class="avatar">${p.avatar}</span><strong>${esc(p.name)}</strong>${p.bot?'<span class="bot-tag">BOT</span>':''}</div>`).join(''):'QR 또는 PIN으로 학생이 입장하면 여기에 표시됩니다.';}
function sortedPlayers(){return Object.values(room?.players||{}).sort((a,b)=>(Number(b.score)||0)-(Number(a.score)||0)||(a.name||'').localeCompare(b.name||'','ko'));}
function renderRanking(){const list=sortedPlayers(),blind=Boolean(room?.blindActive)&&room?.status!=='finished',need=currentRound()?.pairs?.length||room?.config?.pairsPerRound||1;$('rankingList').innerHTML=list.map((p,i)=>{const matched=p.matchedPairIds?.length||0,pct=Math.min(100,matched/need*100);return `<div class="rank-row"><span class="rank-num">${i+1}</span><span class="rank-avatar">${p.avatar||'🐻'}</span><div class="rank-copy"><strong>${esc(p.name)}</strong><span>${matched}/${need}쌍 · 실수 ${p.mistakes||0}회</span><div class="progress-mini"><i style="width:${pct}%"></i></div></div><strong class="rank-score">${blind?'?':(Number(p.score)||0).toLocaleString()}</strong></div>`;}).join('');$('rankBlindCover').classList.toggle('hidden',!blind);$('blindBadge').classList.toggle('hidden',!blind);$('progressText').textContent=`${list.length}명 플레이 중`;}
function renderGame(full=true){if(!room)return;showHostSubView('gameView');const round=currentRound();$('countdownOverlay').classList.toggle('hidden',room.status!=='countdown');$('hostRoundLabel').textContent=`ROUND ${Math.max(1,room.roundIndex+1)}/${room.memory?.roundCount||room.config.roundCount}`;const phase=room.status==='preview'?'MEMORIZE':room.status==='countdown'?'READY':'MATCH';$('phaseBadge').textContent=phase;$('hostPhaseGuide').textContent=room.status==='countdown'?'게임 준비 중입니다.':room.status==='preview'?'학생은 카드 위치를 기억합니다. 교사 화면은 어휘만 공개합니다.':'이번 판 한국어↔몽골어 어휘를 확인하세요.';const players=Object.values(room.players||{}),finished=players.filter(p=>(p.matchedPairIds?.length||0)>=(round?.pairs?.length||999)).length;$('hostMatchedSummary').textContent=`${finished}/${players.length}명 완료`;if(round&&full!==false){$('hostMemoryStrip').innerHTML=(round.pairs||[]).map(pair=>`<div class="host-vocab-pair"><span class="ko">${esc(pair.ko)}</span><b>↔</b><span class="mn">${esc(pair.mn)}</span></div>`).join('');}let remaining=0,duration=1;if(room.status==='preview'){duration=Math.max(1,room.config.previewTime*1000);remaining=Math.max(0,room.previewEndAt-nowMs());}else if(room.status==='playing'){duration=Math.max(1000,room.config.roundTime*1000);remaining=Math.max(0,room.roundEndAt-nowMs());}else if(room.status==='countdown'){duration=3200;remaining=Math.max(0,room.countdownEndAt-nowMs());}const ratio=Math.max(0,Math.min(1,remaining/duration)),timer=$('hostCircleTimer');timer.style.setProperty('--progress',`${ratio*100}%`);timer.style.setProperty('--timer-color',ratio<.2?'#ff4f70':room.status==='preview'?'#ff6fae':'#37d8ff');$('hostTimerText').textContent=(remaining/1000).toFixed(1);renderRanking();}
function renderRoundResult(){if(!room)return;const n=room.roundIndex+1;$('roundResultTitle').textContent=`${n}판 종료`;$('roundResultTimer').textContent=n>=room.memory.roundCount?'최종 결과 집계 중':'다음 판 준비';const top=[...Object.values(room.players)].sort((a,b)=>(Number(b.roundScore)||0)-(Number(a.roundScore)||0)).slice(0,3);$('roundTop3').innerHTML=top.map((p,i)=>`<div class="round-top-item"><b>${['🥇','🥈','🥉'][i]||'⭐'}</b><strong>${esc(p.name)}</strong><span>이번 판 ${(Number(p.roundScore)||0).toLocaleString()}점 · 실수 ${p.mistakes||0}회</span></div>`).join('');}
function renderFinal(){const list=sortedPlayers(),top=list.slice(0,3);$('finalPodium').innerHTML=top.map((p,i)=>`<div class="podium-item rank${i+1}"><div class="avatar">${p.avatar||'🐻'}</div><strong>${esc(p.name)}</strong><span>${(Number(p.score)||0).toLocaleString()}점</span><em>${i+1}위 · 총 실수 ${p.totalMistakes||0}회</em></div>`).join('');$('finalRanking').innerHTML=list.map((p,i)=>`<div class="rank-row"><span class="rank-num">${i+1}</span><span class="rank-avatar">${p.avatar||'🐻'}</span><div class="rank-copy"><strong>${esc(p.name)}</strong><span>총 실수 ${p.totalMistakes||0}회</span></div><strong class="rank-score">${(Number(p.score)||0).toLocaleString()}</strong></div>`).join('');const lucky=ensureLuckyAward(room,list,room.finishedAt||nowMs());renderLuckyAward({anchor:$('finalPodium'),award:lucky.award,eligible:lucky.eligible,onDraw:()=>audio.playLuckyDraw(),onTick:(progress)=>audio.playLuckyTick(progress),onReveal:()=>audio.playLuckyWinner()});if(lucky.changed)persistAndBroadcast();}
async function startSolo(){try{const data=await ensureData(),config=validateConfig(data),memory=buildMemoryRounds(data.items,config);localStorage.setItem('kmb_solo_payload',JSON.stringify({config,memory,title:data.title,at:Date.now()}));window.open('memory-play.html?solo=1','_blank');}catch(e){toast(e.message);}}
async function endRoom(){if(!room)return;if(!confirm('현재 기억력 게임방을 종료할까요?'))return;clearBotTimers();if(bus?.mode==='firebase')await bus.removeRoom();else{bus?.send('room-closed',{});bus?.removeRoom();}bus?.close();bus=null;room=null;if(loop)clearInterval(loop);loop=null;audio.stopAll();location.href='memory-pairs.html';}
function backSetup(){if(room&&Object.keys(room.players||{}).length&&!confirm('대기실을 닫고 설정 화면으로 돌아갈까요?'))return;if(bus?.mode==='local')bus.removeRoom();bus?.close();bus=null;room=null;if(loop)clearInterval(loop);loop=null;clearBotTimers();audio.stopAll();$('hostView').classList.add('hidden');$('setupView').classList.remove('hidden');}

fillCatalog();applyLaunchParams();updateSourceFields();refreshData();updateBackendStatus();
$('sourceType').addEventListener('change',()=>{fillBooks();refreshData();});$('vocabMode').addEventListener('change',refreshData);$('snuBook').addEventListener('change',()=>{fillLessons();refreshData();});$('snuLesson').addEventListener('change',refreshData);$('collocationSet').addEventListener('change',refreshData);$('pairsPerRound').addEventListener('change',refreshData);$('roundCount').addEventListener('change',refreshData);$('previewTime').addEventListener('change',refreshData);$('roundTime').addEventListener('change',refreshData);
$('vocabBtn').addEventListener('click',openVocabModal);$('closeVocabBtn').addEventListener('click',closeVocabModal);$('vocabSearch').addEventListener('input',renderVocabList);$('selectAllBtn').addEventListener('click',()=>{sourceItems.forEach(v=>draftSelection.add(v.id));renderVocabList();});$('clearAllBtn').addEventListener('click',()=>{draftSelection.clear();renderVocabList();});$('applyVocabBtn').addEventListener('click',applyVocabSelection);$('vocabList').addEventListener('change',e=>{const c=e.target.closest('.vocab-check');if(!c)return;const item=sourceItems.find(v=>String(v.id)===c.dataset.id);if(!item)return;c.checked?draftSelection.add(item.id):draftSelection.delete(item.id);renderVocabList();});$('vocabList').addEventListener('click',e=>{const b=e.target.closest('button[data-action]');if(b)handleVocabAction(b.dataset.action,b.dataset.id);});
$('soundTestBtn').addEventListener('click',async()=>{setupAudio();await audio.preview();});$('bgmEnabled').addEventListener('change',()=>{setupAudio();if(room)audio.startBgm(currentMusicMode);});$('sfxEnabled').addEventListener('change',setupAudio);$('masterVolume').addEventListener('input',setupAudio);$('gameBgmBtn').addEventListener('click',()=>{const s=audio.getSettings();audio.setSettings({...s,bgmEnabled:!s.bgmEnabled});$('bgmEnabled').checked=audio.getSettings().bgmEnabled;syncAudioControls();if(audio.getSettings().bgmEnabled)audio.startBgm(currentMusicMode);});$('gameSfxBtn').addEventListener('click',()=>{const s=audio.getSettings();audio.setSettings({...s,sfxEnabled:!s.sfxEnabled});$('sfxEnabled').checked=audio.getSettings().sfxEnabled;syncAudioControls();});
$('createRoomBtn').addEventListener('click',()=>createRoom(false));$('demoBtn').addEventListener('click',()=>createRoom(true));$('soloBtn').addEventListener('click',startSolo);$('addDemoBtn').addEventListener('click',()=>addDemoStudents(10,true));$('startGameBtn').addEventListener('click',startGame);$('backSetupBtn').addEventListener('click',backSetup);$('endRoomBtn').addEventListener('click',endRoom);$('newGameBtn').addEventListener('click',()=>location.href='memory-pairs.html');$('fullscreenBtn').addEventListener('click',()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen?.());
window.addEventListener('beforeunload',()=>{clearBotTimers();if(loop)clearInterval(loop);bus?.close();});
